-- Adds an optional "links" array to amblux_product_pages.required_accessories
-- cards, e.g. {"title": "...", "body": "...", "links": [{"label": "Central
-- Control drivers", "slug": "central-control-driver"}]}. This is how the
-- "Required accessories" section's driver/control mentions become real
-- clickable cross-links to the driver and control family pages, instead of
-- descriptive text with no target.
--
-- Deliberately explicit per-card link lists (authored here) rather than
-- pattern-matching the word "driver" or "switch" out of the body/items text
-- at render time — several cards mention more than one control family
-- ("wired or wireless switch"), so a single inferred link target would
-- often be wrong. recessed-puck's "Choose a faceplate finish" card is left
-- untouched: those are cover-plate SKUs with no product page of their own.
update public.amblux_product_pages set required_accessories = '[{"title": "1. Compatible 24 V driver", "body": "Select the AMBLUX driver according to the total connected wattage for your run (9 W/m).", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}]}, {"title": "2. Choose one compatible control method", "items": ["AMBLUX dimming control system", "Wired or wireless switch", "Door sensor", "Dimming sensor"], "links": [{"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'silicone-6x6';

update public.amblux_product_pages set required_accessories = '[{"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'silicone-4x8.5-trim';

update public.amblux_product_pages set required_accessories = '[{"title": "Required for a complete run", "items": ["AMB-FCRGL-RC1015TR-PC-1.5M — power cord", "AMB-FCRGL-RC1015TR -90DEG-CON — 90° connector", "AMB-FCRGL-RC1015TR -N2N-CON — end-to-end connector", "AMB-FCRGL-RC1015TR -BRKT — installation bracket (optional per run)"]}, {"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'rigid-10x15';

update public.amblux_product_pages set required_accessories = '[{"title": "Required for a complete run", "items": ["AMB-FCRGL-RC0608TR-PC-1.5M — power cord"]}, {"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'rigid-6x8';

update public.amblux_product_pages set required_accessories = '[{"title": "Required for a complete run", "items": ["AMB-FCST-SR1010-45DEG -CLIPS — mounting clips, bag of 10"]}, {"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'silicone-10x10-45deg';

update public.amblux_product_pages set required_accessories = '[{"title": "Required for a complete run", "items": ["AMB-FCRGL-SM-45DEG-PC-1.5M — power cord", "AMB-FCRGL-SM-45DEG -N2N Cbl 15MM — end-to-end cable", "AMB-FCRGL-SM-45DEG -BRKT — installation bracket"]}, {"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'rigid-45deg-surface';

update public.amblux_product_pages set required_accessories = '[{"title": "Required for a complete run", "items": ["AMB-FCRGL-SM1610-PC-1.5M — power cord", "AMB-FCRGL-SM1610-N2N Cbl 15MM — end-to-end cable", "AMB-FCRGL-SM1610 -N2N-CON — end-to-end connector", "AMB-FCRGL-SM1610 -BRKT — installation bracket"]}, {"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'rigid-16x10-surface';

update public.amblux_product_pages set required_accessories = '[{"title": "Choose a compatible driver + control", "body": "Select an AMBLUX driver sized to your total connected wattage, plus one wired or wireless control method.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}, {"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'surface-puck';

update public.amblux_product_pages set required_accessories = '[{"title": "Choose a compatible control", "body": "Pick one or more wired or wireless controls to pair with this driver — see Compatible controls in the specifications below.", "links": [{"label": "Wired controls", "slug": "wired-sensor-controls"}, {"label": "Wireless controls", "slug": "wireless-sensor-controls"}, {"label": "Wireless dimming", "slug": "wireless-dimming-controls"}]}]'::jsonb where slug = 'central-control-driver';

update public.amblux_product_pages set required_accessories = '[{"title": "Requires", "body": "One of the AMBLUX Central Control drivers (24W / 36W / 60W / 96W), sized to your connected wattage.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}]}]'::jsonb where slug = 'wired-sensor-controls';

update public.amblux_product_pages set required_accessories = '[{"title": "Requires", "body": "One of the AMBLUX Central Control drivers (24W / 36W / 60W / 96W), sized to your connected wattage. Switch models also require the AMB-WRLSS-SS-RCVR receiver.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}]}]'::jsonb where slug = 'wireless-sensor-controls';

update public.amblux_product_pages set required_accessories = '[{"title": "Requires", "body": "One of the AMBLUX Central Control drivers (24W / 36W / 60W / 96W), sized to your connected wattage. Kinetic RF switches and the Bluetooth App also require the AMB-DMG-WRLSS-RCVR receiver.", "links": [{"label": "Central Control drivers", "slug": "central-control-driver"}]}]'::jsonb where slug = 'wireless-dimming-controls';
